services:
  cgdf_api:
    build:
      context: .
      dockerfile: infra/Dockerfile_dev
    container_name: cgdf_dev
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    environment:
      - APP_PORT=${APP_PORT:-8000}
    volumes:
      - .:/app