FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download pt_core_news_sm

COPY . .

ENV PYTHONPATH=/app

CMD uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT:-55555}