FROM python:3.11-slim

WORKDIR /app

COPY --from=requirements requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

CMD uvicorn main:app --host 0.0.0.0 --port ${APP_PORT:-55555} --reload