name: CI - Build, Lint and Test

on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    environment: "APP_PORT"
    env:
      APP_PORT: ${{ vars.APP_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Linting Tools
        run: pip install black ruff

      - name: Run style check (Black)
        run: black --check app/

      - name: Run linter (Ruff)
        run: ruff check app/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: |
          docker compose -f docker-compose_prod.yml up --build -d

      - name: Wait for containers to be healthy
        run: sleep 15

      - name: Run unit tests (pytest)
        run: |
          echo "Running unit tests with pytest..."
          # Point pytest to the 'tests/' directory where your files actually are
          docker compose -f docker-compose_prod.yml run --rm cgdf_api pytest tests/ -v

      - name: Shut down containers
        if: always()
        run: docker compose -f docker-compose_prod.yml down -v